package pl.technicalsite.FileComponents.Template.TemplateModel;

import org.springframework.stereotype.Component;
import pl.technicalsite.FileModel.FieldsDto;
import pl.technicalsite.FileModel.FileFieldsBuilder;

@Component
public class Template {

    public static final String NEWLINE = "\n";

    public String createFile(TemplateComponents templateComponents, FileFieldsBuilder fileField) {

        StringBuilder sb = new StringBuilder();

        sb.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>" + NEWLINE);
        sb.append("<xsl:stylesheet xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\" version=\"1.0\"" + NEWLINE);
        sb.append("		xmlns:g=\"http://base.google.com/ns/1.0\">" + NEWLINE);
        sb.append("    <xsl:output method=\"text\"/>" + NEWLINE);
        sb.append("    <xsl:strip-space elements=\"node\"/>" + NEWLINE);
        sb.append("    <xsl:strip-space elements=\"*\" />" + NEWLINE);
        sb.append("" + NEWLINE);
        sb.append("    <xsl:variable name=\"newline\"><xsl:text>&#x0a;</xsl:text></xsl:variable>" + NEWLINE);
        sb.append("    <xsl:variable name=\"sep\"><xsl:text>&#x7f;</xsl:text></xsl:variable>" + NEWLINE);
        sb.append("" + NEWLINE);
        sb.append("    <xsl:template match=\"rss/channel/title | rss/channel/link | rss/channel/description\" />" + NEWLINE);
        sb.append("    <xsl:template match=\"" + templateComponents.getStructure() + "\">" + NEWLINE);
        sb.append("" + NEWLINE);
        sb.append("        <!-- ustawienie zmiennych -->" + NEWLINE);
        sb.append("        <!--EXTERNAL_ID-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getId() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"normalize-space(" + fileField.getId() + ")\">" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--NAME-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getName() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getName() + "),0,100)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--NEW_PRODUCT-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"" + fileField.getNewProductKey() + "\"" + "= \"" + fileField.getNewProductValue() + "\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"1\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:value-of select=\"0\"/>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--AVAILABLE-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"g:availability = \"in stock\"\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"1\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:value-of select=\"0\"/>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--BESTSELLER-->");
        sb.append("        <xsl:choose>");
        sb.append("            <xsl:when test=\"" + fileField.getBestsellerKey() + "\"" + "= \"" + fileField.getBestsellerValue() + "\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"1\"/>");
        sb.append("            </xsl:when>");
        sb.append("            <xsl:otherwise>");
        sb.append("                <xsl:value-of select=\"0\"/>");
        sb.append("            </xsl:otherwise>");
        sb.append("        </xsl:choose>");
        sb.append("        <xsl:value-of select=\"$sep\"/>");
        sb.append("        <!--BRAND-->");
        sb.append("        <xsl:choose>");
        sb.append("            <xsl:when test=\"string-length(" + fileField.getBrand() + ")\">");
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getBrand() + "),0,512)\"/>");
        sb.append("            </xsl:when>");
        sb.append("            <xsl:otherwise>");
        sb.append("                <xsl:text>\\N</xsl:text>");
        sb.append("            </xsl:otherwise>");
        sb.append("        </xsl:choose>");
        sb.append("        <xsl:value-of select=\"$sep\"/>");
        sb.append("        <!--CATEGORIES-->");
        sb.append("        <xsl:choose>");
        sb.append("            <xsl:when test=\"string-length(" + fileField.getCategories() + ")\">");
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getCategories() + "),0,512)\"/>");
        sb.append("            </xsl:when>");
        sb.append("            <xsl:otherwise>");
        sb.append("                <xsl:text>\\N</xsl:text>");
        sb.append("            </xsl:otherwise>");
        sb.append("        </xsl:choose>");
        sb.append("        <xsl:value-of select=\"$sep\"/>");
        sb.append("        <!--CATEGORY_MAIN-->");
        sb.append("        <xsl:choose>");
        sb.append("            <xsl:when test=\"string-length(" + fileField.getCategoryMain() +")\">");
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getCategoryMain() + "),0,200)\"/>");
        sb.append("            </xsl:when>");
        sb.append("            <xsl:otherwise>");
        sb.append("                <xsl:text>\\N</xsl:text>");
        sb.append("            </xsl:otherwise>");
        sb.append("        </xsl:choose>");
        sb.append("        <xsl:value-of select=\"$sep\"/>");
        sb.append("        <!--DESCRIPTION-->");
        sb.append("        <xsl:choose>");
        sb.append("            <xsl:when test=\"string-length(" + fileField.getDescription() + ")\">");
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getDescription() + "),0,1024)\"/>");
        sb.append("            </xsl:when>");
        sb.append("            <xsl:otherwise>");
        sb.append("                <xsl:text>\\N</xsl:text>");
        sb.append("            </xsl:otherwise>");
        sb.append("        </xsl:choose>");
        sb.append("        <xsl:value-of select=\"$sep\"/>");
        sb.append("        <!--DETAIL_1-->");
        sb.append("        <xsl:choose>");
        sb.append("            <xsl:when test=\"string-length(" + fileField.getDetail1() + ")\">");
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getDetail1() + "),0,512)\"/>");
        sb.append("            </xsl:when>");
        sb.append("            <xsl:otherwise>");
        sb.append("                <xsl:text>\\N</xsl:text>");
        sb.append("            </xsl:otherwise>");
        sb.append("        </xsl:choose>");
        sb.append("        <xsl:value-of select=\"$sep\"/>");
//        sb.append("        <!--DETAIL_2-->");
        sb.append("        <xsl:choose>");
        sb.append("            <xsl:when test=\"string-length(" + fileField.getDetail2() + ")\">");
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getDetail2() + "),0,512)\"/>");
        sb.append("            </xsl:when>");
        sb.append("            <xsl:otherwise>");
        sb.append("                <xsl:text>\\N</xsl:text>");
        sb.append("            </xsl:otherwise>");
        sb.append("        </xsl:choose>");
        sb.append("        <xsl:value-of select=\"$sep\"/>");
//        sb.append("        <!--DETAIL_3-->");
        sb.append("        <xsl:choose>");
        sb.append("            <xsl:when test=\"string-length(" + fileField.getDetail3() + ")\">");
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getDetail3() + "),0,512)\"/>");
        sb.append("            </xsl:when>");
        sb.append("            <xsl:otherwise>");
        sb.append("                <xsl:text>\\N</xsl:text>");
        sb.append("            </xsl:otherwise>");
        sb.append("        </xsl:choose>");
        sb.append("        <xsl:value-of select=\"$sep\"/>");
//        sb.append("        <!--DETAIL_4-->");
        sb.append("        <xsl:choose>");
        sb.append("            <xsl:when test=\"string-length(" + fileField.getDetail4() + ")\">");
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getDetail4() + "),0,512)\"/>");
        sb.append("            </xsl:when>");
        sb.append("            <xsl:otherwise>");
        sb.append("                <xsl:text>\\N</xsl:text>");
        sb.append("            </xsl:otherwise>");
        sb.append("        </xsl:choose>");
        sb.append("        <xsl:value-of select=\"$sep\"/>");
//        sb.append("        <!--DETAIL_5-->");
        sb.append("        <xsl:choose>");
        sb.append("            <xsl:when test=\"string-length(" + fileField.getDetail5() + ")\">");
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getDetail5() + "),0,512)\"/>");
        sb.append("            </xsl:when>");
        sb.append("            <xsl:otherwise>");
        sb.append("                <xsl:text>\\N</xsl:text>");
        sb.append("            </xsl:otherwise>");
        sb.append("        </xsl:choose>");
        sb.append("        <xsl:value-of select=\"$sep\"/>");
//        sb.append("        <!--MANUFACTURER-->");
        sb.append("        <xsl:choose>");
        sb.append("            <xsl:when test=\"string-length(" + fileField.getManufacturer() + ")\">");
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getManufacturer() + "),0,100)\"/>");
        sb.append("            </xsl:when>");
        sb.append("            <xsl:otherwise>");
        sb.append("                <xsl:text>\\N</xsl:text>");
        sb.append("            </xsl:otherwise>");
        sb.append("        </xsl:choose>");
        sb.append("        <xsl:value-of select=\"$sep\"/>");
//        sb.append("        <!--PRICE-->");
        sb.append("        <xsl:choose>");
        sb.append("            <xsl:when test=\"string-length(" + fileField.getPrice() + ")\">");
        sb.append("                <xsl:value-of select=\"normalize-space(translate(" + fileField.getPrice() + ", \"" + fileField.getCurrency() + "\", \"\"))\"/>");
        sb.append("            </xsl:when>");
        sb.append("            <xsl:otherwise>");
        sb.append("                <xsl:text>\N</xsl:text>");
        sb.append("            </xsl:otherwise>");
        sb.append("        </xsl:choose>");
        sb.append("        <xsl:value-of select=\"$sep\"/>");
//        sb.append("        <!--PRICE_PROMO-->");
//        sb.append("        <xsl:choose>");
//        sb.append("            <xsl:when test="string-length(g:sale_price)">");
//        sb.append("                <xsl:value-of select="normalize-space(translate(g:sale_price, " EUR", ""))"/>");
//        sb.append("            </xsl:when>");
//        sb.append("            <xsl:otherwise>");
//        sb.append("                <xsl:text>\N</xsl:text>");
//        sb.append("            </xsl:otherwise>");
//        sb.append("        </xsl:choose>");
//        sb.append("        <xsl:value-of select="$sep"/>");
//        sb.append("        <!--QUANTITY-->");
//        sb.append("        <xsl:choose>");
//        sb.append("            <xsl:when test="string-length(UNDEFINED)">");
//        sb.append("                <xsl:value-of select="normalize-space(UNDEFINED)"/>");
//        sb.append("            </xsl:when>");
//        sb.append("            <xsl:otherwise>");
//        sb.append("                <xsl:text>\N</xsl:text>");
//        sb.append("            </xsl:otherwise>");
//        sb.append("        </xsl:choose>");
//        sb.append("        <xsl:value-of select="$sep"/>");
//        sb.append("        <!--URL_PRODUCT-->");
//        sb.append("        <xsl:choose>");
//        sb.append("            <xsl:when test="string-length(link)">");
//        sb.append("                <xsl:value-of select="substring(normalize-space(link),0,512)"/>");
//        sb.append("            </xsl:when>");
//        sb.append("            <xsl:otherwise>");
//        sb.append("                <xsl:text>\N</xsl:text>");
//        sb.append("            </xsl:otherwise>");
//        sb.append("        </xsl:choose>");
//        sb.append("        <xsl:value-of select="$sep"/>");
//        sb.append("        <!--URL_IMG-->");
//        sb.append("        <xsl:choose>");
//        sb.append("            <xsl:when test="string-length(g:image_link)">");
//        sb.append("                <xsl:value-of select="substring(normalize-space(g:image_link),0,512)"/>");
//        sb.append("            </xsl:when>");
//        sb.append("            <xsl:otherwise>");
//        sb.append("                <xsl:text>\N</xsl:text>");
//        sb.append("            </xsl:otherwise>");
//        sb.append("        </xsl:choose>");
//        sb.append("        <xsl:value-of select="$sep"/>");
//        sb.append("        <!--GENDER-->");
//        sb.append("        <xsl:choose>");
//        sb.append("            <xsl:when test="g:gender = "male"">");
//        sb.append("                <xsl:value-of select="1"/>");
//        sb.append("            </xsl:when>");
//        sb.append("            <xsl:otherwise>");
//        sb.append("                <xsl:value-of select="0"/>");
//        sb.append("            </xsl:otherwise>");
//        sb.append("        </xsl:choose>");
//        sb.append("        <xsl:value-of select="$sep"/>");
//        sb.append("        <!--URL_CATEGORY-->");
//        sb.append("        <xsl:choose>");
//        sb.append("            <xsl:when test="string-length(UNDEFINED)">");
//        sb.append("                <xsl:value-of select="normalize-space(UNDEFINED)"/>");
//        sb.append("            </xsl:when>");
//        sb.append("            <xsl:otherwise>");
//        sb.append("                <xsl:text>\N</xsl:text>");
//        sb.append("            </xsl:otherwise>");
//        sb.append("        </xsl:choose>");
//        sb.append("        <xsl:value-of select="$sep"/>");
//        sb.append("        <!--URL_CATEGORY_MARK-->");
//        sb.append("        <xsl:choose>");
//        sb.append("            <xsl:when test="string-length(UNDEFINED)">");
//        sb.append("                <xsl:value-of select="substring(normalize-space(UNDEFINED),0,512)"/>");
//        sb.append("            </xsl:when>");
//        sb.append("            <xsl:otherwise>");
//        sb.append("                <xsl:text>\N</xsl:text>");
//        sb.append("            </xsl:otherwise>");
//        sb.append("        </xsl:choose>");
//        sb.append("        <xsl:value-of select="$sep"/>");
//        sb.append("        <!--POPULARITY-->");
//        sb.append("        <xsl:choose>");
//        sb.append("            <xsl:when test="string-length(UNDEFINED)">");
//        sb.append("                <xsl:value-of select="normalize-space(UNDEFINED)"/>");
//        sb.append("            </xsl:when>");
//        sb.append("            <xsl:otherwise>");
//        sb.append("                <xsl:text>\N</xsl:text>");
//        sb.append("            </xsl:otherwise>");
//        sb.append("        </xsl:choose>");
//        sb.append("        <xsl:value-of select="$sep"/>");
//        sb.append("        <!--SEASON-->");
//        sb.append("        <xsl:choose>");
//        sb.append("            <xsl:when test="string-length(UNDEFINED)">");
//        sb.append("                <xsl:value-of select="substring(normalize-space(UNDEFINED),0,40)"/>");
//        sb.append("            </xsl:when>");
//        sb.append("            <xsl:otherwise>");
//        sb.append("                <xsl:text>\N</xsl:text>");
//        sb.append("            </xsl:otherwise>");
//        sb.append("        </xsl:choose>");
//        sb.append("        <xsl:value-of select="$sep"/>");
//        sb.append("        <!--COLOR-->");
//        sb.append("        <xsl:choose>");
//        sb.append("            <xsl:when test="string-length(g:color)">");
//        sb.append("                <xsl:value-of select="substring(normalize-space(g:color),0,40)"/>");
//        sb.append("            </xsl:when>");
//        sb.append("            <xsl:otherwise>");
//        sb.append("                <xsl:text>\N</xsl:text>");
//        sb.append("            </xsl:otherwise>");
//        sb.append("        </xsl:choose>");
//        sb.append("        <xsl:value-of select="$sep"/>");
//        sb.append("        <!--ADDITIONAL_IMAGE-->");
//        sb.append("        <xsl:choose>");
//        sb.append("            <xsl:when test="string-length(UNDEFINED)">");
//        sb.append("                <xsl:value-of select="substring(normalize-space(UNDEFINED),0,128)"/>");
//        sb.append("            </xsl:when>");
//        sb.append("            <xsl:otherwise>");
//        sb.append("                <xsl:text>\N</xsl:text>");
//        sb.append("            </xsl:otherwise>");
//        sb.append("        </xsl:choose>");
//        sb.append("        <xsl:value-of select="$sep"/>");
//        sb.append("        <!--INT_DETAIL1-->");
//        sb.append("        <xsl:text>\N</xsl:text>");
//        sb.append("        <xsl:value-of select="$sep"/>");
//        sb.append("        <!--INT_DETAIL2-->");
//        sb.append("        <xsl:text>\N</xsl:text>");
//        sb.append("        <xsl:value-of select="$sep"/>");
//        sb.append("        <!--DEC_DETAIL1-->");
//        sb.append("        <xsl:text>\N</xsl:text>");
//        sb.append("        <xsl:value-of select="$sep"/>");
//        sb.append("        <!--array-->");
//        sb.append("        <xsl:text>\N</xsl:text>");
//        sb.append("        <!-- koniec -->");
//        sb.append("        <xsl:value-of select="$newline"/>");
//        sb.append("    </xsl:template>");
//        sb.append("</xsl:stylesheet>");

        return sb.toString();
    }

}
