package pl.technicalsite.FileComponents.Template.TemplateModel;

import org.springframework.stereotype.Component;
import pl.technicalsite.FileModel.FieldsBuilder;

@Component
public class Template {

    public static final String NEWLINE = "\n";

    public String createFile(TemplateComponents templateComponents, FieldsBuilder fileField) {

        StringBuilder sb = new StringBuilder();

        sb.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>" + NEWLINE);
        sb.append("<xsl:stylesheet xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\" version=\"1.0\"" + NEWLINE);
        sb.append("		xmlns:g=\"http://base.google.com/ns/1.0\">" + NEWLINE);
        sb.append("    <xsl:output method=\"text\"/>" + NEWLINE);
        sb.append("    <xsl:strip-space elements=\"node\"/>" + NEWLINE);
        sb.append("    <xsl:strip-space elements=\"*\" />" + NEWLINE);
        sb.append("" + NEWLINE);
        sb.append("    <xsl:variable name=\"newline\"><xsl:text>&#x0a;</xsl:text></xsl:variable>" + NEWLINE);
        sb.append("    <xsl:variable name=\"sep\"><xsl:text>&#x7f;</xsl:text></xsl:variable>" + NEWLINE);
        sb.append("" + NEWLINE);
        sb.append("    <xsl:template match=\"rss/channel/title | rss/channel/link | rss/channel/description\" />" + NEWLINE);
        sb.append("    <xsl:template match=\"" + templateComponents.getStructure() + "\">" + NEWLINE);
        sb.append("" + NEWLINE);
        sb.append("        <!-- ustawienie zmiennych -->" + NEWLINE);
        sb.append("        <!--EXTERNAL_ID-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getId() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"normalize-space(" + fileField.getId() + ")\">" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--NAME-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getName() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getName() + "),0,100)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--NEW_PRODUCT-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"" + fileField.getNewProductKey() + "\"" + "= \"" + fileField.getNewProductValue() + "\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"1\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:value-of select=\"0\"/>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--AVAILABLE-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"g:availability = \"in stock\"\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"1\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:value-of select=\"0\"/>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--BESTSELLER-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"" + fileField.getBestsellerKey() + "\"" + "= \"" + fileField.getBestsellerValue() + "\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"1\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:value-of select=\"0\"/>" + NEWLINE);
        sb.append("            </xsl:otherwise>");
        sb.append("        </xsl:choose>");
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--BRAND-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getBrand() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getBrand() + "),0,512)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--CATEGORIES-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getCategories() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getCategories() + "),0,512)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>");
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--CATEGORY_MAIN-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getCategoryMain() +")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getCategoryMain() + "),0,200)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--DESCRIPTION-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getDescription() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getDescription() + "),0,1024)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--DETAIL_1-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getDetail1() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getDetail1() + "),0,512)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--DETAIL_2-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getDetail2() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getDetail2() + "),0,512)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--DETAIL_3-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getDetail3() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getDetail3() + "),0,512)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--DETAIL_4-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getDetail4() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getDetail4() + "),0,512)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--DETAIL_5-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getDetail5() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getDetail5() + "),0,512)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>");
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--MANUFACTURER-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getManufacturer() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getManufacturer() + "),0,100)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--PRICE-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getPrice() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"normalize-space(translate(" + fileField.getPrice() + ", \"" + fileField.getCurrency() + "\", \"\"))\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--PRICE_PROMO-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getPricePromo() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"normalize-space(translate(" + fileField.getPricePromo() + ", \"" + fileField.getCurrency() + "\", \"\"))\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--QUANTITY-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getQuantity() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getQuantity() + "),0,100)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--URL_PRODUCT-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getUrlProduct() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getUrlProduct() + "),0,512)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>");
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>");
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--URL_IMG-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getUrlImg() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getUrlImg() + "),0,512)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--GENDER-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"" + fileField.getGenderKey() + " = \"" + fileField.getGenderValue() + "\"\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"1\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>");
        sb.append("                <xsl:value-of select=\"0\"/>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--URL_CATEGORY-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getUrlCategory() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getUrlCategory() + "),0,512)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--URL_CATEGORY_MARK-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getUrlCategory() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getUrlCategory() + "),0,512)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--POPULARITY-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getPopularity() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getPopularity() + "),0,512)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--SEASON-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getSeason() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getSeason() + "),0,40)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--COLOR-->" + NEWLINE);
        sb.append("        <xsl:choose>" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getColor() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getColor() + "),0,40)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>" + NEWLINE);
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--ADDITIONAL_IMAGE-->" + NEWLINE);
        sb.append("            <xsl:when test=\"string-length(" + fileField.getAddidtionalImage() + ")\">" + NEWLINE);
        sb.append("                <xsl:value-of select=\"substring(normalize-space(" + fileField.getAddidtionalImage() + "),0,128)\"/>" + NEWLINE);
        sb.append("            </xsl:when>" + NEWLINE);
        sb.append("            <xsl:otherwise>");
        sb.append("                <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("            </xsl:otherwise>" + NEWLINE);
        sb.append("        </xsl:choose>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--INT_DETAIL1-->" + NEWLINE);
        sb.append("        <xsl:text>\\N</xsl:text>");
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--INT_DETAIL2-->" + NEWLINE);
        sb.append("        <xsl:text>\\N</xsl:text>");
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--DEC_DETAIL1-->" + NEWLINE);
        sb.append("        <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$sep\"/>" + NEWLINE);
        sb.append("        <!--array-->" + NEWLINE);
        sb.append("        <xsl:text>\\N</xsl:text>" + NEWLINE);
        sb.append("        <!-- koniec -->" + NEWLINE);
        sb.append("        <xsl:value-of select=\"$newline\"/> + NEWLINE");
        sb.append("    </xsl:template>" + NEWLINE);
        sb.append("</xsl:stylesheet>" + NEWLINE);

        return sb.toString();
    }

}
